---
- name: install and start apache
  hosts: centos 
  become: yes
  tasks:
  - name: Latest apache version installation
    yum:	
      name: httpd
      state: latest 
  - name: Apache enabled and running
    systemd:
      name: httpd
      enabled: true
      state: started
  - name: copy index.html
    copy:
      src: ~/ansible/index.html
      dest: /var/www/html/
