---
- name: output facts
  hosts: centos
#i  gather_fact: true
  tasks:
  - name: print Ansible facts
    debug:
      msg: The default IPv4 address of {{ ansible_fqdn }} is {{ ansible_eth1.ipv4.address }}
