---
- name: manage httpd.conf
  hosts: centos
  become: yes
  tasks:
  - name: copy httpd.conf
    copy:
      src: httpd.conf
      dest: /etc/httpd/conf/httpd.conf
    notify: restart_httpd
  handlers:
  - name: restart_httpd
    systemd:
      name: httpd
      state: restarted  
