---
- name: hash demo 
  hosts: centos01
  become: yes
  tasks:
  - name: Create user from hash
    user:
      name: "{{item.name}}" 
      groups: "{{item.groups}}" 
      state: present
      comment: "{{item.commentaire}}"
    loop:
    - { name: 'janexxx1',groups: 'wheel',commentaire: 'Joe Doe' }
    - { name: 'joexxxx1',groups: 'root', commentaire: 'KKKKK' }
