---
- name: Installs a package and prints the result
  hosts: ubuntu
  become: True
  tasks:
  - name: Install the package
    apt: 
      name: apache2
      state: present
    register: install_result
  - debug: var=install_result
